apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
 disableNameSuffixHash: true

namespace: grafana-app-dashboard

bases:
- ../../base

resources:
  - namespace.yaml
  - namespace-groups.yaml

configMapGenerator:
- files:
    - dashboards/amq.json
  name: dashboard-amq
- files:
    - dashboards/pvc.json
  name: dashboard-pvc
- files:
    - dashboards/pod-containers.json
  name: dashboard-pod-containers

# use the field 'issuer' as OAUTH_ISSUER from following command
# oc run --rm -i -t box --image=registry.redhat.io/ubi8-minimal --restart=Never -- curl https://openshift.default.svc/.well-known/oauth-authorization-server --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
- literals:
  - OAUTH_ISSUER=https://oauth-openshift.apps.cluster-1d9e.gcp.testdrive.openshift.com
  name: oauth-issuer
- files:
    - app-rules.yaml
  name: app-rules

# I'm changing the names to match the namespace name.
# Please change "grafana-app-dashboard" prefix to match your namespace name
patches:
- target:
    kind: ClusterRoleBinding
    name: grafana-proxy
  patch: |-
    - op: replace
      path: /metadata/name
      value: grafana-app-dashboard-proxy
    - op: replace
      path: /subjects/0/namespace
      value: grafana-app-dashboard
- target:
    kind: ClusterRoleBinding
    name: grafana-cluster-monitoring-view
  patch: |-
    - op: replace
      path: /metadata/name
      value: grafana-app-dashboard-cluster-monitoring-view
    - op: replace
      path: /subjects/0/namespace
      value: grafana-app-dashboard
- target:
    kind: Group
    name: namespace-admins
  patch: |-
    - op: replace
      path: /metadata/name
      value: grafana-app-dashboard-admins
- target:
    kind: Group
    name: namespace-users
  patch: |-
    - op: replace
      path: /metadata/name
      value: grafana-app-dashboard-users
- target:
    kind: RoleBinding
    name: namespace-admins-rb
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: grafana-app-dashboard-admins
- target:
    kind: RoleBinding
    name: namespace-users-rb
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: grafana-app-dashboard-users

patchesStrategicMerge:
- patch-grafana-deployment.yaml
