apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  annotations:
    #serviceaccounts.openshift.io/oauth-redirecturi.grafana:  "auth/callback/openshift"
    serviceaccounts.openshift.io/oauth-redirectreference.grafana: "{\"kind\":\"OAuthRedirectReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"Route\",\"name\":\"grafana\"}}"
