apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-grafana-ds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generate-grafana-ds-token-job-role
subjects:
  - kind: ServiceAccount
    name: generate-grafana-ds-token-job-sa
