apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generate-grafana-ds-token-job-role
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - secrets
      - configmaps
      - pods
    verbs:
      - get
      - list
      - patch
      - delete
