apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: grafana
    weight: 100
